name: Build and publish

on:
  push:
    branches: [master]

env:
  NODE_VERSION: 12.x

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install, build
      run: |
        yarn install --frozen-lockfile
        yarn build
    - name: Cache build
      uses: actions/cache@v2
      with:
        path: ./*
        key: ${{ github.sha }}
    - name: Test
      run: yarn test

  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Restore cache
      uses: actions/cache@v2
      with:
        path: ./*
        key: ${{ github.sha }}
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.MERGE_RELEASE_GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      uses: mikeal/merge-release@master

  deploy-website:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Restore build cache
      uses: actions/cache@v2
      with:
        path: ./*
        key: ${{ github.sha }}
    - name: Install, build & prepare
      run: |
        cd gallery
        yarn --frozen-lockfile
        yarn build
        echo 'ui.aragon.org' > dist/CNAME
        cp public/favicon.svg dist
    - name: Push to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./gallery/dist
